language: node_js
node_js:
  - lts/*
install:
  - yarn --frozen-lockfile
script:
  - node --version
  - echo "Testing Started ..."
  - yarn test
  - echo "Testing Finished."
  - echo "NPM Deploying Started ..."
   - yarn --version
   - yarn build
   - echo "NPM Building Finished."
cache: yarn
deploy:
  provider: npm
  email: git@hexie.uu.me
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branche: master
    
