language: node_js
node_js:
- lts/*
install:
- yarn
script:
- yarn publish
cache: yarn
deploy:
  provider: npm
  email: git@hexie.uu.me
  api_key:
    secure:  25dd0695-c28a-4cee-8d66-eea3da22d9f0
  on:
    branch: master
  skip-cleanup: true
