language: node_js
node_js:
- lts/*
install:
- yarn --frozen-lockfile
stages:
 - test
 - name: deploy

jobs:
 include:
   - stage: test
     script:
       - node --version
       - echo "Testing Started ..."
       - yarn test
       - echo "Testing Finished."

   - stage: deploy
     script:
       - echo "NPM Deploying Started ..."
       - yarn version
       - yarn build
       - echo "NPM Building Finished."

     deploy:
       provider: npm
       email: git@hexie.uu.me
       api_key: "$NPM_TOKEN"
       skip_cleanup: true
       on:
         branche: master
      skip-cleanup: true
      