language: node_js
node_js:
- lts/*
install:
- yarn
script:
- yarn test
cache: yarn
deploy:
  provider: npm
  email: git@hexie.uu.me
  api_key:
    secure:  e8c56ceb-86f6-47ef-96ba-019ef767a0f6
  on:
    branch: master
  skip-cleanup: true
